### ISSUE TITLE
List student names in CSV as "Last, First" rather than "First Last"

### ISSUE THREAD

**Issue by chrispittman** [longhornopen/canvas-peer-grade-calculator#1]

**Comment by nhaithuy** [comment]
![Screen Shot 2021-04-08 at 12 16 44 PM](https://user-images.githubusercontent.com/44341725/114069288-73177200-9864-11eb-8b7c-a625b7fb0678.png)
The name format has been changed to Last, First.

**Comment by chrispittman** [comment]
Confirmed fixed.  Thanks, Thuy!
