### ISSUE TITLE
Help with set-up

### ISSUE THREAD

**Issue by mlincoln** [longhornopen/canvas-peer-grade-calculator#6]
I'm trying to run the tool locally connected to an LTI key on our Canvas Test instance.
When I run `php artisan serve`, I get back `Server running on [http://127.0.0.1:8000].`

Should I use http://127.0.0.1:8000/oauth_redirect_complete for the redirect URI (instead of http://localhost:8000/oauth_redirect_complete)?

In my .env file, should I use APP_URL=http://127.0.0.1:8000 ?

When I use these settings, and navigate to http://127.0.0.1:8000 in my browser, I see:
`{"error":"invalid_request","error_description":"redirect_uri does not match client settings"}`
And when I try to add the app to a course using the client ID, I get 
`Could not find an LTI configuration for client ID xxxx`

**Comment by chrispittman** [comment]
Locally, you can use either 'localhost' or '127.0.0.1' as your host.  But whatever you pick, you should use it consistently in both the APP_URL setting, and in the redirect URI you give to Canvas.

Canvas now gives you two flavors of Developer Key - an 'API Key' and an 'LTI Key'.  Make this an 'API Key' - looks like you picked 'LTI Key' instead.  (This isn't an LTI tool - it's a separate web site that uses Canvas as a login source.)  I'll update the README to match what the Canvas UI now looks like.

**Comment by mlincoln** [comment]
Thanks, your readme was already clear here, and I did use an API key. 

I'm guessing that I should be following these steps [https://community.canvaslms.com/t5/Instructor-Guide/How-do-I-configure-an-external-app-for-a-course-using-a-client/ta-p/1071] to approximate what your app store is doing in the installation steps here [https://utexas.instructure.com/courses/633028/pages/how-do-i-use-the-peer-review-grading-tool-in-canvas?module_item_id=9288217], is that correct?

I think my issue is that I believe you're supposed to enter an _LTI_ developer key in that dialog box, not an API key, so perhaps there's a different process I should be following to get the integration in a course.

**Comment by chrispittman** [comment]
This isn't an LTI tool (an 'external app', in Canvas's terminology).  It's just a website.  You can include it as a link in a course if you want, same as any other link, (which is what our App Store does), but it's not a tool that needs to be configured.  It's just a web site you go to, which redirects you to Canvas to log on, and then makes Canvas API calls on your behalf.

**Comment by mlincoln** [comment]
Ah, I see. I got it working locally now, thanks!
