### ISSUE TITLE
CSV export columns do not match headers

### ISSUE THREAD

**Issue by mlincoln** [longhornopen/canvas-peer-grade-calculator#7]
I set this up locally to run against our Canvas test instance, and when I downloaded the CSV export, a few things seem to be off:

1. The headers do not appear to match the column contents. Here is the content of my test CSV:
```
Student | ID | SIS User ID | peer review 1(8511235)
Student 1 | Student 2 | 8 | 4.66666667
Student 1 | Student 3 | 5 | 4.66666667
Student 1 | Student 4 | 1 | 4.66666667
Student 2 | Student 1 | 9 | 7.5
Student 2 | Student 3 | 6 | 7.5
Student 3 | Student 1 | 10 | 8.5
Student 3 | Student 2 | 7 | 8.5
```

It appears that:
- The column with the header "ID" actually contains the grader name
- The column with the header "SIS User ID" actually contains the grade assigned by that grader

2. When I tried to import my CSV to the gradebook, I received this error: "The CSV header row is invalid."

3. I expected to receive a CSV with one row for each student, and instead I received a row for each student-grader pairing. Based on the helper text _"The "Grades Only" option will be in the correct format to upload into the Canvas gradebook. Use this option if you want to manually change grades, and upload them back to Canvas."_ I would expect there to be a single row for each student with the average grade that could be edited before importing--maybe the gradebook import will allow multiple rows for the same student if the duplicate rows have the same value, but in that case, I think the instructor would need to edit the grade in multiple rows for the gradebook to import it successfully.

**Comment by chrispittman** [comment]
I'll look into the first item (column header mismatch).

For the second and third items, I don't think that CSV is supposed to be in the Canvas gradebook format - if you want these grades as-is, you should be able to use the 'Import Scores to Gradebook' button and have them automatically get uploaded.  The 'Export Scores to CSV' button was intended more for faculty who want to a more exotic form of grade-calculation than we support natively...they can just download our raw data and drop it into Excel on their own.  Does that address these two items?  If not, what's the use case for exporting this data in the Canvas-gradebook format?

**Comment by chrispittman** [comment]
Okay, I think I understand the comment on item 3 now.  (I didn't write this one and am trying to track down somebody who knows peer grading better than me for comment.)

**Comment by mlincoln** [comment]
Thanks @chrispittman! Your interpretation of the case for "export scores to CSV" makes sense to me. I was confused because the app says "The "Grades Only" option will be in the **correct format to upload into the Canvas gradebook**."

I'd suggest modifying that text if the feature expects instructors to do some massaging to get the data into a format that Canvas will accept.

**Comment by chrispittman** [comment]
Yeah, I think we just had a miscommunication between the original developer and the original requester about what this export should actually do.  Trying to track down one of them to decide whether it's the implementation or the documentation that's wrong.

**Comment by chrispittman** [comment]
It looks like this was just an oversight.  The popup message should be correct now - the 'Grades Only' export should now be ready to import into the Canvas Gradebook.
